#include includes/valueAnalysis.properties

CompositeCPA.cpas = cpa.location.LocationCPA, cpa.callstack.CallstackCPA, cpa.functionpointer.FunctionPointerCPA, cpa.value.GreyboxValueAnalysisCPA, cpa.constraints.ConstraintsCPA, cpa.unknownfunccall.UnknownFuncCallCPA

cpa.value.unknownValueHandling = INTRODUCE_SYMBOLIC

analysis.algorithm.greyboxSymbolicExecution = true

daikonChecker.greyboxObjectFileStrings = /usr/lib64/libm.so
